{
 "title": "Triton Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mean Latency per Request (over a 30-sec window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / (1+rate(nv_inference_request_success[30s])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Compute Time per Request (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(rate(nv_inference_compute_input_duration_us[30s]) + rate(nv_inference_compute_infer_duration_us[30s]) + rate(nv_inference_compute_output_duration_us[30s])) / (1 + rate(nv_inference_request_success[30s])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization [%]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{gpu_uuid=~\".+\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Ratio  (Total Queue Time /Total Compute Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / (1 + rate(nv_inference_compute_input_duration_us[30s]) + rate(nv_inference_compute_infer_duration_us[30s]) + rate(nv_inference_compute_output_duration_us[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  }
 ]
}